CC=g++

all: classes.x inheritance.x overloading.x abstract.x

classes.x: classes.cpp 
	${CC} classes.cpp -o classes.x

inheritance.x: inheritance.cpp
	${CC} inheritance.cpp -o inheritance.x

overloading.x: overloading.cpp
	${CC} overloading.cpp -o overloading.x

abstract.x: abstract.cpp
	${CC} abstract.cpp -o abstract.x
	
clean:
	rm *.x